#!/usr/bin/env php
<?php
// Use composers autoload.php if available
if (file_exists(dirname(__FILE__) . '/../vendor/autoload.php')) {
    require_once dirname(__FILE__) . '/../vendor/autoload.php';
} elseif (file_exists(dirname(__FILE__) . '/../../../autoload.php')) {
    require_once dirname(__FILE__) . '/../../../autoload.php';
}

use SeleniumSetup\Config\ConfigFactory;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

error_reporting(E_ERROR | E_PARSE | E_COMPILE_ERROR);

$greetings = <<<'BANNER'
 ____            ___
/\  _`\         /\_ \                  __
\ \,\L\_\     __\//\ \      __    ___ /\_\  __  __    ___ ___
 \/_\__ \   /'__`\\ \ \   /'__`\/' _ `\/\ \/\ \/\ \ /' __` __`\
   /\ \L\ \/\  __/ \_\ \_/\  __//\ \/\ \ \ \ \ \_\ \/\ \/\ \/\ \
   \ `\____\ \____\/\____\ \____\ \_\ \_\ \_\ \____/\ \_\ \_\ \_\
    \/_____/\/____/\/____/\/____/\/_/\/_/\/_/\/___/  \/_/\/_/\/_/
    Selenium Environment on Windows, Linux and Mac
    by Bogdan Anton and contributors.

BANNER;

$console = new Application('Selenium Setup', '4.0.0');


$console
    ->register('start')
    ->setDescription('Start Selenium server with all supported drivers attached to it.')
    ->setDefinition(array(
        new InputOption('config', 'c', InputOption::VALUE_OPTIONAL, 'Path to your Selenium configuration options.')
    ))
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($greetings) {
        $output->writeln($greetings);
        $config = ConfigFactory::createFromConfigFile(\SeleniumSetup\Config\ConfigFactory::DEFAULT_CONFIGURATION_FILE);
        $c = new \SeleniumSetup\SeleniumSetupApp($config, $input, $output);
        $c->startServer();
    });

$console
    ->register('stop')
    ->setDescription('Stop Selenium server.')
    ->setDefinition(array(
        new InputArgument('serverName', 'sn', InputOption::VALUE_REQUIRED, 'The name of the server you want to shut down.')
    ))
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($greetings) {
        $config = ConfigFactory::createFromConfigFile(\SeleniumSetup\Config\ConfigFactory::DEFAULT_CONFIGURATION_FILE);
        $c = new \SeleniumSetup\SeleniumSetupApp($config, $input, $output);
        $c->stopServer();
    });

$console
    ->register('list')
    ->setDescription('List all running servers.')
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($greetings) {
        $config = ConfigFactory::createFromConfigFile(\SeleniumSetup\Config\ConfigFactory::DEFAULT_CONFIGURATION_FILE);
        $c = new \SeleniumSetup\SeleniumSetupApp($config, $input, $output);
        $c->listServers();
    });


$console->run();
